### ISSUE TITLE
Empty input file message - even in standard flow

### ISSUE THREAD

**Issue by GPadley** [HPCE/hpce-2018-cw6#11]
Running both standard_flow.sh and optimised_flow.sh in have the output message which I am unable to find within the code base. Is this something that should be worried about?

![image](https://user-images.githubusercontent.com/17782581/54706838-c3192400-4b37-11e9-939f-d377f738a5ea.png)

**Comment by jjd06** [comment]
This is coming from `libjpeg`. It looks like this message is popping out when an attempt is made to access the "(last + 1)th" JPEG in an MJPEG stream. This is expected and handled correctly, but unfortunately the message isn't suppressed. So, nothing to worry about.
