### ISSUE TITLE
Abstract and Introduction

### ISSUE THREAD

**Issue by luisi-at** [HPCE/hpce-2018-cw6#14]
Though not specified in the requirements, would it aid with the flow of the report to include an abstract and introduction, as provided in the IEEE template? Or, is it advised to completely avoid this and use the space to consolidate the analyses and proposal?

Thanks.

**Comment by jjd06** [comment]
Personally I wouldn't bother with a title, author list, abstract or introduction. You don't need any of it, and all just takes away valuable space from other things.

Note that I pointed to IEEEtran as an example of reasonable font sizes, etc. only, not as a report structure guideline.

**Comment by luisi-at** [comment]
Ok, thank you.
