### ISSUE TITLE
Make all on Canned Environment

### ISSUE THREAD

**Issue by GPadley** [HPCE/hpce-2018-cw6#4]
Within the WIndows 10 canned MinGW environment, when I run `make all` I get this error code. Trying to use `pacman` to install `libjpeg-dev` isn't working, is there anyway to install the library known of?

![image](https://user-images.githubusercontent.com/17782581/53953392-208a8b00-40cb-11e9-8ebb-3d4b7851b079.png)

Thanks, George

**Comment by jjd06** [comment]
Does [this](https://pzuk.wordpress.com/2012/03/02/how-to-compile-libjpeg-using-mingw/) help?

**Comment by GPadley** [comment]
Yeah, that's enabled the make all to run. Thank you.

**Comment by samuraisoldier** [comment]
I followed the link and installed the library and make all now runs, however the script seems to still have an issue? I'm not sure exactly what is causing this.

`$ scripts/standard_flow.sh media/big_buck_bunny_scene_small.mp4  random  all  10  1
+ SRC=media/big_buck_bunny_scene_small.mp4
+ EVENTS=random
+ FRAMES=
+ [[ 5 -ge 3 ]]
+ FRAMES=all
+ OVERSAMPLE=100
+ [[ 5 -ge 4 ]]
+ OVERSAMPLE=10
+ VIS=0
+ [[ 5 -ge 5 ]]
+ [[ 1 == \1 ]]
+ VIS=1
+ BASE=media/big_buck_bunny_scene_small
+ mkdir -p media/big_buck_bunny_scene_small/w
+ WORKING=media/big_buck_bunny_scene_small/w
+ scripts/video_to_mjpeg.sh media/big_buck_bunny_scene_small.mp4 all
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.0 (Rev3, Built by MSYS2 project)
  configuration: --prefix=/mingw64 --target-os=mingw32 --arch=x86_64 --disable-debug --disable-static --enable-dxva2 --enable-d3d11va --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libcaca --enable-libcelt --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-libwebp --enable-openal --enable-libwavpack --enable-pic --enable-postproc --enable-runtime-cpudetect --enable-shared --enable-static --enable-swresample --enable-version3 --enable-zlib --enable-libaom --disable-doc
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, avi, from 'media/big_buck_bunny_scene_small.mp4':
  Metadata:
    encoder         : MEncoder VERSION
  Duration: 00:00:19.52, start: 0.000000, bitrate: 808 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 720x432 [SAR 1:1 DAR 5:3], 803 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0000025c9e965f80] deprecated pixel format used, make sure you did set range correctly
Output #0, mjpeg, to 'pipe:':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 720x432 [SAR 1:1 DAR 5:3], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=  487 fps=0.0 q=0.0 Lsize=   28412kB time=00:00:16.23 bitrate=14337.8kbits/s speed=16.6x
video:28412kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
+ [[ random == '' ]]
+ [[ random == \r\a\n\d\o\m ]]
+ EVENTS=media/big_buck_bunny_scene_small/w/objects.events
+ bin/generate_object_stream
Premature end of JPEG file
Empty input file
+ cp media/big_buck_bunny_scene_small/w/objects.events media/big_buck_bunny_scene_small.true.events
+ bin/frame_insert_objects media/big_buck_bunny_scene_small/w/objects.events
Inserting objects into frame.
Premature end of JPEG file
Empty input file
+ [[ 1 == 1 ]]
+ bin/frame_highlight_objects media/big_buck_bunny_scene_small/w/objects.events
Highlighting objects in frame.
Premature end of JPEG file
Invalid JPEG file structure: missing SOS marker
+ bin/frame_to_object_stream
Classifying frames from stdin, writing to stdout.
Premature end of JPEG file
Invalid JPEG file structure: missing SOS marker
+ [[ 1 == 1 ]]
+ bin/frame_highlight_objects media/big_buck_bunny_scene_small.ref.events
Highlighting objects in frame.
Premature end of JPEG file
Invalid JPEG file structure: missing SOS marker
+ bin/frame_to_spikes
Reading frame
Premature end of JPEG file
Invalid JPEG file structure: missing SOS marker
Stream finished
+ bin/spikes_to_frame
+ bin/frame_to_object_stream
Classifying frames from stdin, writing to stdout.
Empty input file
+ [[ 1 == 1 ]]
+ bin/frame_highlight_objects media/big_buck_bunny_scene_small.spiking.events
Highlighting objects in frame.
Empty input file
+ bin/frame_subsample 10
Subsampling frames from stdin to stdout.
Premature end of JPEG file
Invalid JPEG file structure: missing SOS marker
+ bin/frame_to_object_stream
Classifying frames from stdin, writing to stdout.
Empty input file
+ bin/object_stream_stretch 10
+ [[ 1 == 1 ]]
+ bin/frame_highlight_objects media/big_buck_bunny_scene_small.trad.events
Highlighting objects in frame.
Premature end of JPEG file
Invalid JPEG file structure: missing SOS marker
+ [[ 1 == 1 ]]
+ ffmpeg -y -i media/big_buck_bunny_scene_small/w/objects-true.mjpeg -i media/big_buck_bunny_scene_small/w/objects-ref-detected.mjpeg -i media/big_buck_bunny_scene_small/w/objects-spiking-detected.mjpeg -i media/big_buck_bunny_scene_small/w/objects-trad-detected.mjpeg -filter_complex '[0:v][1:v]hstack=inputs=2[top];[2:v][3:v]hstack=inputs=2[bottom];[top][bottom]vstack=inputs=2[v]' -map '[v]' media/big_buck_bunny_scene_small/w/objects-detected-all.mp4
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.0 (Rev3, Built by MSYS2 project)
  configuration: --prefix=/mingw64 --target-os=mingw32 --arch=x86_64 --disable-debug --disable-static --enable-dxva2 --enable-d3d11va --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libcaca --enable-libcelt --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-libwebp --enable-openal --enable-libwavpack --enable-pic --enable-postproc --enable-runtime-cpudetect --enable-shared --enable-static --enable-swresample --enable-version3 --enable-zlib --enable-libaom --disable-doc
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mjpeg @ 00000250b4097100] Format mjpeg detected only with low score of 1, misdetection possible!
[mjpeg @ 00000250b4097100] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mjpeg, from 'media/big_buck_bunny_scene_small/w/objects-true.mjpeg':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 1200k tbn, 25 tbc
[mjpeg @ 00000250b40ab4c0] Format mjpeg detected only with low score of 1, misdetection possible!
[mjpeg @ 00000250b40ab4c0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #1, mjpeg, from 'media/big_buck_bunny_scene_small/w/objects-ref-detected.mjpeg':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 1200k tbn, 25 tbc
[mjpeg @ 00000250b40b5500] Format mjpeg detected only with low score of 1, misdetection possible!
[mjpeg @ 00000250b40b5500] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #2, mjpeg, from 'media/big_buck_bunny_scene_small/w/objects-spiking-detected.mjpeg':
  Duration: N/A, bitrate: N/A
    Stream #2:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 1200k tbn, 25 tbc
[mjpeg @ 00000250b40c7440] Format mjpeg detected only with low score of 1, misdetection possible!
[mjpeg @ 00000250b40c7440] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #3, mjpeg, from 'media/big_buck_bunny_scene_small/w/objects-trad-detected.mjpeg':
  Duration: N/A, bitrate: N/A
    Stream #3:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 1200k tbn, 25 tbc
Stream mapping:
  Stream #0:0 (mjpeg) -> hstack:input0
  Stream #1:0 (mjpeg) -> hstack:input1
  Stream #2:0 (mjpeg) -> hstack:input0
  Stream #3:0 (mjpeg) -> hstack:input1
  vstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
Cannot determine format of input stream 0:0 after EOF
Error marking filters as finished
Conversion failed!
`
