### ISSUE TITLE
Objective of coursework

### ISSUE THREAD

**Issue by MerelyLogical** [HPCE/hpce-2018-cw6#6]
I got a bit confused by the wordings of the specifications.

Are we supposed to propose a solution speeding up the entire procedure, i.e., from the start to the end of `standard_flow.sh`, or

the two simulations, one optimised flow for spiked simulation, and another for the traditional simulation?

In other words, would it be helpful for the clients if we proposed optimisations for other parts of the procedure such as `frame_insert_objects`, `video_to_mjpeg`, and `ffmpeg`?

Thanks.

**Comment by jjd06** [comment]
The goal (as far as the client is concerned) is to accelerate normal use, i.e. `standard_flow.sh`.

There may be things you can propose to speed up external library calls, e.g. `ffmpeg`, but do bear in mind that these are already going to be far more optimised than the custom parts of the code base.
