### ISSUE TITLE
How to parallelise multiple execution in Shell

### ISSUE THREAD

**Issue by CliveWongTohSoon** [HPCE/hpce-2018-cw6#7]
We see the opportunity to parallelise the streaming of `objects.mjpeg` to the `bin/frame_to_object_stream`, `bin/frame_to_spikes` and `bin/frame_subsample` respectively. However, we struggled to get it to work, which we believe is our lack of knowledge in Linux Shell.  Below is the snippet of our command.

```
bin/frame_insert_objects ${EVENTS} < ${WORKING}/input.mjpeg | \
    tee ${WORKING}/objects.mjpeg | { <&0 bin/frame_to_object_stream &> ${BASE}.ref.events &
        bin/frame_to_spikes | bin/spikes_to_frame | tee ${WORKING}/objects-spiking.mjpeg | bin/frame_to_object_stream &> ${BASE}.spiking.events &
        bin/frame_subsample ${OVERSAMPLE} | bin/frame_to_object_stream | bin/object_stream_stretch ${OVERSAMPLE} &> ${BASE}.trad.events &
        wait
    }
```
We believe it is the writing to standard output part that breaks this parallelisation (?). Could you enlighten us on how to get it properly implemented?

**Comment by tnugent97** [comment]
I think that first pipe is just going to redirect the output from the `bin/frame_insert_objects` executable.
If you use `cat` and `tee` together, I think you can do what you want:
```bash
cat file.txt | tee >(pbcopy) >(do_stuff) >(do_more_stuff) | grep errors
```
(https://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands)
You'll have to be careful about the outputs though.

 It might be easier to rewrite the C++ to write to a file instead of stdout or just `cat objects.mjpeg` into one executable that calls the functions you want.

**Comment by CliveWongTohSoon** [comment]
Does it not change the actual functions? So we are allowed to write to a file directly in C++ instead of writing to the stdout?

**Comment by tnugent97** [comment]
You can do whatever you want :) 
If you are specifically referring to the first part of the report, I believe code changes are allowed as long as they are quick changes / help uncover other bottlenecks. There is even a suggestion in the README that TBB can be used:

> Adding TBB, streaming parallelism, or OpenCL in low-risk / low-effort / high-impact places (though it is unlikely one would consider OpenCL low-effort or low-risk).

I don't think there are any strict guidelines on what you do, as long as you can justify it in the report.

**Comment by CliveWongTohSoon** [comment]
Thanks, I managed to fix it by using `tee >(pbcopy)` you mentioned.

**Comment by CliveWongTohSoon** [comment]
Even though tee >( ) method works to parallelise tasks, I notice I I will get `unbound variable` error if trying to parallelise too many task, in this case I try to parallelise:
```
tee data >(task1) \
    >(task2) \
    >(task3) \
    >(task4) \
    >(task5) \
    >(task6) >/dev/null
```
in which each taskN might or might not have parallel tasks running. This will results in the following error code:
```
-bash: $1: unbound variable
+++ shell_session_update
+++ shell_session_save
+++ '[' -n /Users/clivewongtohsoon/.bash_sessions/43CEA6BB-E5F1-4A4B-A19E-14E65B1CF861.session ']'
+++ echo -n 'Saving session...'
Saving session...+++ umask 077
++++ /bin/date +%s
+++ echo 'echo Restored session: "$(/bin/date -r 1553165182)"'
+++ declare -F shell_session_save_user_state
+++ shell_session_history_allowed
+++ '[' -n /Users/clivewongtohsoon/.bash_sessions/43CEA6BB-E5F1-4A4B-A19E-14E65B1CF861.historynew ']'
+++ local allowed=0
+++ shopt -q histappend
-bash: HISTTIMEFORMAT: unbound variable
```

I suspected I might not have enough threads or cores to support the number of tasks I intend to parallelise, and tried to split task1-3 in 1 tee and 4-6 into another tee, but I still get similar error. May I know what I am missing here? Maybe I need to do something to close the threads at the end of pipe or there is a maximum pipe tee can support?
